apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHk5ZWpjemlt
  CLOUDINARY_KEY: NzM2NzUyNzk1NDEyNjc3
  CLOUDINARY_SECRET: WDBJYlJ1ZGlrNkdsaGtnb3BBUEx4dy0wQTNF
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZWE5vYjJzd09UZ2lMQ0poSWpvaVkyMXZObTVoWm1Gc01UUXlhekp6Y1hCMlkzaDBOVEpyZFNKOS5EaFZDaXdKTllzNlVDZlB0WUNZdHN3
  DB_URL: bW9uZ29kYitzcnY6Ly9hc2hva21hbWlkaTkxMF9kYl91c2VyOnQzUkVkOVNFZ1RJTURCUG9AY2x1c3RlcjAuZDViYXhmdi5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==

